apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: doris-test
  name: doris-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doris-test
  template:
    metadata:
      labels:
        app: doris-test
    spec:
      containers:
      - image: dorisfebrianda93/testing-argocicd:20
        name: doris-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: doris-test
  name: doris-test
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: doris-test
  type: ClusterIP
